#!/bin/bash

#2) Process reference and query genome
#2.1) Remove fragments and retain chromosomes only
cat refgenome.fa | grep ">chr" | sed s/">"//g > refgenome_chr_names.txt
samtools faidx refgenome.fa -r refgenome_chr_names.txt > refgenome_chr.fa
cat qrygenome.fa | grep ">chr" | sed s/">"//g > qrygenome_chr_names.txt
samtools faidx qrygenome.fa -r qrygenome_chr_names.txt > qrygenome_chr.fa
#2.1.2) If the fasta files have messy headline, remove spacer and pick a unique column
cat refgenome.fa | cut -f 1 -d " " > ref.fa #This separates by a space, retains the first column.
cat refgenome.fa | grep ">CM" | cut -f 1 -d " " | sed s/">"//g > ref_chr_names.txt
